// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGjZSUxgrm8KGrqCbm-6QWtsMpbC9KXjo',
    appId: '1:498046811560:web:ffe0ce99f59f7cdc1f719d',
    messagingSenderId: '498046811560',
    projectId: 'flutterproject-5d342',
    authDomain: 'flutterproject-5d342.firebaseapp.com',
    storageBucket: 'flutterproject-5d342.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_0RzTersukHNTAK28jN7bEG2Duz_YAI',
    appId: '1:498046811560:android:74775405b6c046fb1f719d',
    messagingSenderId: '498046811560',
    projectId: 'flutterproject-5d342',
    storageBucket: 'flutterproject-5d342.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6dCDv04j2Fy-xCrveXuu07wGnhHmWTxc',
    appId: '1:498046811560:ios:8518247514b555711f719d',
    messagingSenderId: '498046811560',
    projectId: 'flutterproject-5d342',
    storageBucket: 'flutterproject-5d342.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6dCDv04j2Fy-xCrveXuu07wGnhHmWTxc',
    appId: '1:498046811560:ios:8518247514b555711f719d',
    messagingSenderId: '498046811560',
    projectId: 'flutterproject-5d342',
    storageBucket: 'flutterproject-5d342.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGjZSUxgrm8KGrqCbm-6QWtsMpbC9KXjo',
    appId: '1:498046811560:web:4f727f81afc8a6d01f719d',
    messagingSenderId: '498046811560',
    projectId: 'flutterproject-5d342',
    authDomain: 'flutterproject-5d342.firebaseapp.com',
    storageBucket: 'flutterproject-5d342.firebasestorage.app',
  );
}
